config/routes.rb
Rails.application.routes.draw do
  resources :user_ads

  devise_for :clients

  devise_for :staffs
  root 'films#index'
  #resources :homes
  resources :films
  resources :offers

  resources :user_laps
  resources :posts
  resources :contacts

  resources :cinemalists
  
end

app/models/user_ad.rb
class UserAd < ApplicationRecord
end

app/controllers/user_ads_controller.rb
class UserAdsController < ApplicationController
  before_action :set_user_ad, only: [:show, :edit, :update, :destroy]

  # GET /user_ads
  # GET /user_ads.json
  def index
    @user_ads = UserAd.all
  end

  # GET /user_ads/1
  # GET /user_ads/1.json
  def show
  end

  # GET /user_ads/new
  def new
    @user_ad = UserAd.new
  end

  # GET /user_ads/1/edit
  def edit
  end

  # POST /user_ads
  # POST /user_ads.json
  def create
    @user_ad = UserAd.new(user_ad_params)

    respond_to do |format|
      if @user_ad.save
        format.html { redirect_to @user_ad, notice: 'User ad was successfully created.' }
        format.json { render :show, status: :created, location: @user_ad }
      else
        format.html { render :new }
        format.json { render json: @user_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_ads/1
  # PATCH/PUT /user_ads/1.json
  def update
    respond_to do |format|
      if @user_ad.update(user_ad_params)
        format.html { redirect_to @user_ad, notice: 'User ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_ad }
      else
        format.html { render :edit }
        format.json { render json: @user_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_ads/1
  # DELETE /user_ads/1.json
  def destroy
    @user_ad.destroy
    respond_to do |format|
      format.html { redirect_to user_ads_url, notice: 'User ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_ad
      @user_ad = UserAd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_ad_params
      params.require(:user_ad).permit(:name, :email)
    end
end

app/helpers/user_ads_helper.rb
module UserAdsHelper
end

app/views/user_ads/_form.html.erb
<%= form_for(user_ad) do |f| %>
  <% if user_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_ad.errors.count, "error") %> prohibited this user_ad from being saved:</h2>

      <ul>
      <% user_ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_ads/edit.html.erb
<h1>Editing User Ad</h1>

<%= render 'form', user_ad: @user_ad %>

<%= link_to 'Show', @user_ad %> |
<%= link_to 'Back', user_ads_path %>

app/views/user_ads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Ads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_ads.each do |user_ad| %>
      <tr>
        <td><%= user_ad.name %></td>
        <td><%= user_ad.email %></td>
        <td><%= link_to 'Show', user_ad %></td>
        <td><%= link_to 'Edit', edit_user_ad_path(user_ad) %></td>
        <td><%= link_to 'Destroy', user_ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Ad', new_user_ad_path %>

app/views/user_ads/new.html.erb
<h1>New User Ad</h1>

<%= render 'form', user_ad: @user_ad %>

<%= link_to 'Back', user_ads_path %>

app/views/user_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_ad.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_ad.email %>
</p>

<%= link_to 'Edit', edit_user_ad_path(@user_ad) %> |
<%= link_to 'Back', user_ads_path %>