config/routes.rb
Rails.application.routes.draw do
  resources :user_ads

  devise_for :clients

  devise_for :staffs
  root 'films#index'
  #resources :homes
  resources :films
  resources :offers

  resources :user_laps
  resources :posts
  resources :contacts

  resources :cinemalists
  
end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImageUploader

  def self.search(keyword)
    Offer.where('name like ?', "%#{keyword}%")
  end
  def self.search3(keyword)
    Offer.where('prix like ?', "%#{keyword}%")
  end
  def self.search2(keyword)
    Offer.where('detail like ?', "%#{keyword}%")
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    keyword = params[:keyword]
    if params[:bt1]
      @offers = Offer.search(keyword)
    elsif params[:bt3]
      @offers = Offer.search3(keyword)
    else
      @offers = Offer.search2(keyword)
    end
  end

  def create
    name = params[:offer][:name]
    prix = params[:offer][:prix]
    time = params[:offer][:time]
    detail = params[:offer][:detail]
    image = params[:offer][:image]

    offer = Offer.create(name: name, prix: prix, time: time, detail: detail, image: image)

    if (offer.nil?)
      render 'new'
    else
      redirect_to offers_path
    end
  end

  def new
    @offer = Offer.new
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    offer = Offer.find(params[:id])
    offer.name = params[:offer][:name]
    offer.prix = params[:offer][:prix]
    offer.time = params[:offer][:time]
    offer.detail = params[:offer][:detail]
    offer.image = params[:offer][:image]

    if (offer.save)
      redirect_to offer_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    redirect_to offers_path
  end

end

app/views/offers/destroy.js.erb
$('.delete_pony').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/offers/edit.html.erb
<div class="form row">
  <h1><i class="fa fa-pencil"></i></h1>
    <font size ="4" face="Courier New" color="green">
      <p class="login__title"><h1>EDIT OFFER<br></h1>
        <%= form_for @offer do |f| %>
          <div class="field-wrap">
              <%= f.label :name %>
              <%= f.text_field :name, class:"form__name"%><br />
              <%= f.label :prix %>
              <%= f.text_field :prix, class:"form__name"%><br />
              <%= f.label :time %>
              <%= f.text_field :time, class:"form__name"%><br />
              <%= f.label :detail %>
              <%= f.text_field :detail, class:"form__name"%><br />
              <%= f.file_field :image %><br />
              <br />
              <%= f.submit class:"btn btn-md btn--warning" %>

              <div class="movie__btns">
                    <button class="btn btn-md btn--warning"><%= link_to "Cancel", offers_path %></button>
              </div>

          </div>
        <% end %>
</div>

app/views/offers/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#hide").click(function(){
        $("table").hide();
    });
    $("#show").click(function(){
        $("table").show();
    });
});
</script>

<button class="btn btn-md btn--warning" id="hide">Hide table</button>
<button class="btn btn-md btn--warning" id="show">Show table</button>

<a ng-mouseover="openDropdownMenu('adminDropdown')"
   ng-mouseleave="closeDropdownMenu('adminDropdown')">

<div class="row">
<table class="table">
  <tr>
      <th>#</th>
      <th>Name</th>
      <th>Prix</th>
      <th>Time</th>
      <th>Detail</th>
      <th>create</th>

  </tr>

  <% @offers.each do |offer| %>
  <tr onmouseover="onMouseOver(this)" >
      <td><%= offer.id %></td>
      <td><%= offer.name %></td>
      <td><%= offer.prix %></td>
      <td><%= offer.time %></td>
      <td><%= offer.detail %></td>
      <td><%= offer.created_at %></td>
      <td>
        <th><%= link_to "Show", offer_path(offer.id) %></th>
        <th><%= link_to "Edit", edit_offer_path(offer.id) %></th>
        <td><%= link_to "Destroy", offer_path(offer.id),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
        </button>
      </td>
  </tr>
  <% end %>

</table>
</div>
</a>



<% if client_signed_in? %>
  Logged in as <strong><%= current_client.email %></strong>.
  <%= link_to 'Edit profile', edit_client_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_client_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Client - Sign up", new_client_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Client - Login", new_client_session_path, :class => 'navbar-link'  %>
<% end %>


<h1 id="text" onmouseover="mouseOver()" onmouseout="mouseOut()" style="text-align:center;">Best Offers</h1>

<script>
function mouseOver() {
    document.getElementById("text").style.color = "red";
}

function mouseOut() {
    document.getElementById("text").style.color = "blue";
}
</script>

<div class="col-sm-1 col-md-1 movie-mobile">
</div>
<div class="movie__btns">
  <button class="btn btn-md btn--warning"><%= link_to "New offers", new_offer_path %></button>
</div>


  <%= form_tag offers_path, class: "form-inline", method: :get do %>
  <div class="col-sm-1 col-md-1 movie-mobile">
  </div>

    <div class="form-group">
      <label for="">Search</label>
      <input type="text" class="form-control" name="keyword">
    </div>

    <button type="submit" class="btn btn-primary" name="bt1">By name</button>
    <button type="submit" class="btn btn-primary" name="bt3">By prix</button>
    <button type="submit" class="btn btn-primary" name="bt2" >By detail</button>
  <% end %>

<% @offers.each do |offer| %>
<tr onmouseover="onMouseOver(this)" >
  <div class="movie movie--preview movie--full release">
      <div class="col-sm-1 col-md-1 movie-mobile">
      </div>

      <div class="col-sm-8 col-md-4 movie-mobile">
          <%= image_tag offer.image_url %>
      </div>

      <div class="col-sm-8 col-md-6">
              <h1 class="page-heading"><%=offer.name%></h1>
              <th><%= link_to "Show", offer_path(offer.id) %></th>
              <p class="movie__option"><strong>Prix:</strong> <%= offer.prix %> </p>
              <p class="movie__option"><strong>Time: </strong><%= offer.time %> <br/></p>
              <p class="movie__option"><strong>Detail: </strong><%= offer.detail %> <br/></p>
      </div>
  </div>
</tr>
<% end %>
</div>
</a>

app/views/offers/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("button").click(function(){
        var x = $("form").serializeArray();
        $.each(x, function(i, field){
            $("#results").append(field.name + ":" + field.value + " ");
        });
    });
});
</script>

<div class="wrapper">
     <div class="col-sm-12">
          <div class="movie">
               <h2 class="page-heading"><%=@offer.name%></h2>
          </div>
      </div>
</div>

<div class="col-sm-4 col-md-3 movie-mobile">
  <% unless @offer.image_url.nil? %><%= image_tag @offer.image_url %><%end%>
</div>

<div class="col-sm-8 col-md-6">
        <p class="movie__time"><strong>Prix:</strong> <%= @offer.prix %> <br/></p>
        <p class="movie__option"><strong>Time: </strong><%= @offer.time %> <br/></p>
        <p class="movie__option"><strong>Detail: </strong><%= @offer.detail %> <br/></p>

        <div class="movie__btns">
              <button class="btn btn-md btn--warning"><%= link_to "MENU", offers_path %></button>
              <button class="btn btn-md btn--warning"><%= link_to "Edit", edit_offer_path %></button>
              <button class="btn btn-md btn--warning">
              <td><%= link_to "Destroy", offer_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
              </button>
        </div>
</div>

<form action="">
  Comment: <input type="text" name="Comment">
</form>

<button class="btn btn-md btn--warning">Commit</button>

<div id="results"></div>