config/routes.rb
Rails.application.routes.draw do
  resources :user_ads

  devise_for :clients

  devise_for :staffs
  root 'films#index'
  #resources :homes
  resources :films
  resources :offers

  resources :user_laps
  resources :posts
  resources :contacts

  resources :cinemalists
  
end

app/views/layouts/_custom.html.erb
<meta charset="utf-8">
<meta name="description" content="A Template by Gozha.net">
<meta name="keywords" content="HTML, CSS, JavaScript">
<meta name="author" content="Gozha.net">
<!-- Mobile Specific Metas-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="telephone=no" name="format-detection">

<!-- Fonts -->
<!-- Font awesome - icon font -->
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<!-- Roboto -->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,700' rel='stylesheet' type='text/css'>
<!-- Open Sans -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:800italic' rel='stylesheet' type='text/css'>

<!-- Stylesheets -->

<!-- Mobile menu -->
<link href="http://amovie.gozha.net/css/gozha-nav.css" rel="stylesheet"/>
<!-- Select -->
<link href="http://amovie.gozha.net/css/external/jquery.selectbox.css" rel="stylesheet"/>

<!-- REVOLUTION BANNER CSS SETTINGS -->
<link rel="stylesheet" type="text/css" href="http://amovie.gozha.net/rs-plugin/css/settings.css" media="screen"/>

<!-- Custom -->
<link href="http://amovie.gozha.net/css/style.css?v=1" rel="stylesheet"/>

<!-- Modernizr -->
<script src="http://amovie.gozha.net/js/external/modernizr.custom.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

app/views/layouts/_footer.html.erb
<footer class="footer-wrapper">
    <section class="container">
        <div class="col-xs-4 col-md-2 footer-nav">
            <ul class="nav-link">
                <li>
                    <a href="#" class="nav-link__item">Cities</a>
                </li>
                <li>
                    <a href="movie-list-left.html" class="nav-link__item">Movies</a>
                </li>
                <li>
                    <a href="trailer.html" class="nav-link__item">Trailers</a>
                </li>
                <li>
                    <a href="rates-left.html" class="nav-link__item">Rates</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-4 col-md-2 footer-nav">
            <ul class="nav-link">
                <li>
                    <a href="coming-soon.html" class="nav-link__item">Coming soon</a>
                </li>
                <li>
                    <a href="cinema-list.html" class="nav-link__item">Cinemas</a>
                </li>
                <li>
                    <a href="offers.html" class="nav-link__item">Best offers</a>
                </li>
                <li>
                    <a href="news-left.html" class="nav-link__item">News</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-4 col-md-2 footer-nav">
            <ul class="nav-link">
                <li>
                    <a href="#" class="nav-link__item">Terms of use</a>
                </li>
                <li>
                    <a href="gallery-four.html" class="nav-link__item">Gallery</a>
                </li>
                <li>
                    <a href="contact.html" class="nav-link__item">Contacts</a>
                </li>
                <li>
                    <a href="page-elements.html" class="nav-link__item">Shortcodes</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="footer-info">
                <p class="heading-special--small">A.Movie<br>
                    <span class="title-edition">in the social media</span>
                </p>

                <div class="social">
                    <a href='#' class="social__variant fa fa-facebook"></a>
                    <a href='#' class="social__variant fa fa-twitter"></a>
                    <a href='#' class="social__variant fa fa-vk"></a>
                    <a href='#' class="social__variant fa fa-instagram"></a>
                    <a href='#' class="social__variant fa fa-tumblr"></a>
                    <a href='#' class="social__variant fa fa-pinterest"></a>
                </div>

                <div class="clearfix"></div>
                <p class="copy">&copy; A.Movie, 2013. All rights reserved. Done by Olia Gozha</p>
            </div>
        </div>
    </section>
</footer>


<!-- JavaScript-->
    <!-- jQuery 1.9.1-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://amovie.gozha.net/js/external/jquery-1.10.1.min.js"><\/script>')</script>
    <!-- Migrate -->
    <script src="http://amovie.gozha.net/js/external/jquery-migrate-1.2.1.min.js"></script>
    <!-- Bootstrap 3-->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

    <!-- jQuery REVOLUTION Slider -->
    <script type="text/javascript" src="http://amovie.gozha.net/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="http://amovie.gozha.net/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

    <!-- Mobile menu -->
    <script src="http://amovie.gozha.net/js/jquery.mobile.menu.js"></script>
     <!-- Select -->
    <script src="http://amovie.gozha.net/js/external/jquery.selectbox-0.2.min.js"></script>
    <!-- Stars rate -->
    <script src="http://amovie.gozha.net/js/external/jquery.raty.js"></script>

    <!-- Form element -->
    <script src="http://amovie.gozha.net/js/external/form-element.js"></script>
    <!-- Form validation -->
    <script src="http://amovie.gozha.net/js/form.js"></script>

    <!-- Twitter feed -->
    <script src="http://amovie.gozha.net/js/external/twitterfeed.js"></script>

    <!-- Custom -->
    <script src="http://amovie.gozha.net/js/custom.js"></script>

    <script type="text/javascript">
          $(document).ready(function() {
            init_Home();
          });
    </script>

app/views/layouts/_header.html.erb
<!-- Header section -->
<header class="header-wrapper header-wrapper--home">
    <div class="container">
        <!-- Logo link-->
        <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag("logo.png") %>
        <% end %>
      </a>
      </div>
        <!-- Main website navigation-->
        <nav id="navigation-box">
            <!-- Toggle for mobile menu mode -->
            <a href="#" id="navigation-toggle">
                <span class="menu-icon">
                    <span class="icon-toggle" role="button" aria-label="Toggle Navigation">
                        <span class="lines"></span>
                    </span>
                </span>
            </a>
            <!-- Link navigation -->
            <ul id="navigation">
                <li>
                    <span class="sub-nav-toggle plus"></span>
                    <%= link_to "Films", films_path %>
                    <ul>
                        <%= link_to "New", new_film_path %>

                    </ul>
                </li>
                <li>
                    <span class="sub-nav-toggle plus"></span>
                    <%= link_to "Offers", offers_path %>
                    <ul>
                        <%= link_to "New", new_offer_path %>

                    </ul>
                </li>
                <li>
                    <span class="sub-nav-toggle plus"></span>
                    <%= link_to "Cinema-lists", cinemalists_path %>
                    <ul>
                        <%= link_to "New", new_cinemalist_path %>
                    </ul>
                </li>
                <li>
                    <span class="sub-nav-toggle plus"></span>
                    <a href="gallery-four.html">Gallery</a>
                    <ul>
                        <li class="menu__nav-item">
                            <a href="gallery-four.html">4 col gallery</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="gallery-three.html">3 col gallery</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="gallery-two.html">2 col gallery</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <span class="sub-nav-toggle plus"></span>
                    <%= link_to "News", posts_path %>
                    <ul>
                        <li class="menu__nav-item">
                            <a href="news-left.html">News (rigth sidebar)</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="news-right.html">News (left sidebar)</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="news-full.html">News (full widht)</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="single-page-left.html">Single post (rigth sidebar)</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="single-page-right.html">Single post (left sidebar)</a>
                        </li>
                        <li class="menu__nav-item">
                            <a href="single-page-full.html">Single post (full widht)</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
    </nav>

    <!-- Additional header buttons / Auth and direct link to booking-->
    <div class="control-panel">
      <% if staff_signed_in? %>
        <div class="auth auth--home">
            <div class="auth__show">
                <span class="auth__image">
                    <img alt="" src="http://placehold.it/31x31">
                </span>
            </div>
            <a href="#" class="btn btn--sign btn--singin">
                <%= current_staff.email %>
            </a>
            <ul class="auth__function">
                <li>
                    <%= link_to 'Edit profile', edit_staff_registration_path, class:"auth__function-item" %>
                </li>
                <li>
                    <%= link_to "Logout", destroy_staff_session_path, method: :delete, class:"auth__function-item"  %>
                </li>
            </ul>

        </div>
        <% else %>
          <%= link_to "Sign up", new_staff_registration_path, class:"btn btn-md btn--warning btn--book btn-control--home "  %> |
          <%= link_to "Login", new_staff_session_path, class:"btn btn-md btn--warning btn--book btn-control--home "  %>
        <% end %>


    </div>

</div>
</header>

<!-- Slider -->
<div class="bannercontainer">
<div class="banner">
    <ul>
      <li data-transition="fade" data-slotamount="7" class="slide" data-slide='Rush.'>
          <img alt='' src="assets/a.jpg">
          <div
              class="caption slide__name margin-slider"
              data-x="right"
              data-y="80"
              data-splitin="chars"
              data-elementdelay="0.1"
              data-speed="700"
              data-start="1400"
              data-easing="easeOutBack"
              data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:0;transformOrigin:50% 50%;"
              data-frames="{ typ :lines;
                                   elementdelay :0.1;
                                   start:1650;
                                   speed:500;
                                   ease:Power3.easeOut;
                                   animation:x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:1;transformPerspective:600;transformOrigin:50% 50%;
                                   },
                                   { typ :lines;
                                   elementdelay :0.1;
                                   start:2150;
                                   speed:500;
                                   ease:Power3.easeOut;
                                   animation:x:0;y:0;z:0;rotationX:00;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:1;transformPerspective:600;transformOrigin:50% 50%;
                                   }
                                   "
              data-splitout="lines"
              data-endelementdelay="0.1"
              data-customout="x:-230;y:0;z:0;rotationX:0;rotationY:0;rotationZ:90;scaleX:0.2;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%"
              data-endspeed="500"
              data-end="8400"
              data-endeasing="Back.easeIn">
              RUSH
          </div>

          <div class="caption slide__time margin-slider sfr str" data-x="right" data-hoffset='-243' data-y="186" data-speed="300" data-start="2100" data-easing="easeOutBack" data-endspeed="300" data-end="8700" data-endeasing="Back.easeIn">
              From
          </div>
          <div class="caption slide__date margin-slider lfb ltb" data-x="right" data-hoffset='-149' data-y="186" data-speed="500" data-start="2400" data-easing="Power4.easeOut" data-endspeed="400" data-end="8200" data-endeasing="Back.easeIn">
              October 18
          </div>
          <div class="caption slide__time margin-slider sfr str" data-x="right" data-hoffset='-113' data-y="186" data-speed="300" data-start="2100" data-easing="easeOutBack" data-endspeed="300" data-end="8700" data-endeasing="Back.easeIn">
              - till
          </div>
          <div class="caption slide__date margin-slider lfb ltb" data-x="right" data-y="186" data-speed="500" data-start="2800" data-easing="Power4.easeOut" data-endspeed="400" data-end="8200" data-endeasing="Back.easeIn">
              November 01
          </div>
          <div
              class="caption slide__text margin-slider customin customout"
              data-x="right"
              data-y="250"
              data-customin="x:0;y:100;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:3;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:0% 0%;"
              data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-speed="400"
              data-start="3000"
              data-endspeed="400"
              data-end="8000"
              data-endeasing="Back.easeIn">
              Two-time Academy Award winner Ron Howard, teams once again with fellow two-time Academy<br>
              Award nominee, writer Peter Morgan , on Rush, a spectacular big-screen re-creation of the merciless<br>
              1970s rivalry between James Hunt and Niki Lauda.
          </div>
          <div
              class="caption margin-slider skewfromright customout "
              data-x="right"
              data-y="324"
              data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
              data-speed="400"
              data-start="3300"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-end="7700"
              data-endeasing="Power4.easeOut">
              <a href="#" class="slide__link">check out cinemas &amp; time</a>
          </div>
      </li>
        

        <li data-transition="fade" data-slotamount="7" class="slide" data-slide='Stop wishing.
Start doing.'>
            <img alt='' src="assets/b.jpg">
            <div
                class="caption slide__name slide__name--smaller slide__name--specific customin customout"
                data-x="left"
                data-y="160"
                data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                data-speed="700"
                data-start="1400"
                data-easing="easeOutBack"
                data-endspeed="500"
                data-end="8600"
                data-endeasing="Back.easeIn">
                Stop
                <span class="highlight">wishing.</span>
                Start
                <span class="highlight">doing.</span>
            </div>

            <div
                class="caption slide__descript customin customout"
                data-x="left"
                data-y="240"
                data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                data-speed="700"
                data-start="2000"
                data-endspeed="500"
                data-end="8400"
                data-endeasing="Back.easeIn">
                find your best match movie with A.MOVIE
            </div>

        </li>

    </ul>
</div>
</div>
<!--end slider -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Cinema</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="wrapper">
            <%= render 'layouts/custom' %>
            <%= render 'layouts/header' %>
            <%= yield %>
            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>